### ISSUE TITLE
Store user and role information in same collection

### ISSUE THREAD

**Issue by FelschR** [FelschR/aspnetcore-identity-documentdb#4]
DocumentDB is billed by collections. Using 2 collections means twice the cost at the cheapest price tier which is especially an issue for smaller development teams.

Storing both user and role information in the same table will make the library more accessible to smaller development teams and should have a minimal impact on the performance.

**Comment by FelschR** [comment]
Implemented in 28eff535dc0abfd9bbc8461e2015b97badec40c1

**Comment by javaadpatel** [comment]
DocumentDB has recently switched to a model where you can have multiple collections that use the same database throughput, so you wouldn't necessarily pay anything extra if you were running in this setup.

Just thought i'd mention this incase there could be improvements made by having users and roles in two different collections
